SERVICE_USER	= ticket-api
SERVICE_GROUP	= www-data

APACHE_CONFIG_ROOT = /etc/apache2
SERVER_ROOT = /var/www/html/ticketapi

APACHE_CONFIG_CHMOD		= 0644
SERVER_ROOT_CHMOD			= 0755
SERVER_CONFIG_CHMOD		= 0400
SERVER_BIN_CHMOD			= 0750

APACHE_CONFIG_INSTALL_FLAGS	= -o root -g root
SERVER_INSTALL_FLAGS				= -o $(SERVICE_USER) -g $(SERVICE_GROUP)
